#version: '3'
#
#services:
##  elasticsearch:
##    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.1
##    environment:
##      - discovery.type=single-node
##    ports:
##      - "9200:9200"
##    networks:
##      - elk
##    volumes:
##      - esdata:/usr/share/elasticsearch/data
##
##  logstash:
##    image: docker.elastic.co/logstash/logstash:7.12.0
##    ports:
##      - "5044:5044"
##      - "5000:5000"
##    volumes:
##      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
##    networks:
##      - elk
##
##  kibana:
##    image: docker.elastic.co/kibana/kibana:7.11.1
##    ports:
##      - "5601:5601"
##    networks:
##      - elk
##    environment:
##      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
##      - server.host=0.0.0.0
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - elk
#
#  spring:
#    image: 058264467328.dkr.ecr.ap-northeast-2.amazonaws.com/mountaincc-server:latest
#    ports:
#      - "8080:8080"
#    environment:
##      - ELASTICSEARCH_HOST=http://elasticsearch:9200
#      - SPRING_DATA_REDIS_HOST=redis
#      - SPRING_DATA_REDIS_PORT=6379
#    depends_on:
##      - elasticsearch
#      - redis
##    networks:
##      - elk
#
#volumes:
#  esdata:
#    driver: local
#
#networks:
#  elk:
#    driver: bridge
